//inputParamsMultInputImagesConsts.h
//Scott Grauer-Gray
//September 29, 2010
//Constants for the input parameters with multiple images...

#ifndef INPUT_PARAMS_MULT_INPUT_IMAGES_CONSTS
#define INPUT_PARAMS_MULT_INPUT_IMAGES_CONSTS

//give the 'index' of each parameter in the input...
const int IMAGES_FILE_PATH_BASE_INDEX_MULT_INPUT_IMAGES = 1;
const int START_IMAGE_NUM_INDEX_MULT_INPUT_IMAGES = 2; 
const int END_IMAGE_NUM_INDEX_MULT_INPUT_IMAGES = 3;
const int FILE_EXTENSION_INDEX_MULT_INPUT_IMAGES = 4;

const int MOTION_IMAGE_FILE_SAVE_INDEX_MULT_INPUT_IMAGES = 5;
const int WIDTH_INPUT_IMAGES_INDEX_MULT_INPUT_IMAGES = 6;
const int HEIGHT_INPUT_IMAGES_INDEX_MULT_INPUT_IMAGES = 7;
const int NUM_BELIEF_PROP_LEVELS_INDEX_MULT_INPUT_IMAGES = 8;
const int NUM_ITERS_PER_BELIEF_PROP_LEVEL_INDEX_MULT_INPUT_IMAGES = 9;
const int DATA_COST_CAP_INDEX_MULT_INPUT_IMAGES = 10;
const int SMOOTHNESS_COST_CAP_INDEX_MULT_INPUT_IMAGES = 11;

const int DATA_COST_WEIGHT_INDEX_MULT_INPUT_IMAGES = 12;
const int CURR_MOVE_INCR_X_INDEX_MULT_INPUT_IMAGES = 13;
const int CURR_MOVE_INCR_Y_INDEX_MULT_INPUT_IMAGES = 14;
const int SAMPLING_LEVEL_INDEX_MULT_INPUT_IMAGES = 15;
const int X_MOVE_MIN_INDEX_MULT_INPUT_IMAGES = 16;
const int X_MOVE_MAX_INDEX_MULT_INPUT_IMAGES = 17;
const int Y_MOVE_MIN_INDEX_MULT_INPUT_IMAGES = 18;
const int Y_MOVE_MAX_INDEX_MULT_INPUT_IMAGES = 19;

const int MOTION_DISPLAY_RANGE_INDEX_MULT_INPUT_IMAGES = 20;
const int GROUND_TRUTH_MOVE_FLO_INDEX_MULT_INPUT_IMAGES = 21;
const int MOTION_MOVE_FLO_INDEX_MULT_INPUT_IMAGES = 22;
const int PROP_CHANGE_MOVE_INDEX_MULT_INPUT_IMAGES = 23;
const int SMOOTHING_SIGMA_INDEX_MULT_INPUT_IMAGES = 24;

//constants related to the estimated movement
const int EST_MOVE_CAP_INDEX_MULT_INPUT_IMAGES = 25;
const int EST_MOVE_WEIGHT_INDEX_MULT_INPUT_IMAGES = 26;

const int NUM_LEVEL_WITHIN_LEV_PYR_HIERARCH_INDEX_MULT_INPUT_IMAGES = 27;

//constant representing 'null'
//const char* NULL_CONST_MULT_INPUT_IMAGES = "null";

#endif //INPUT_PARAMS_MULT_INPUT_IMAGES_CONSTS

