//inputParamsGivenExpMotionConsts.h
//Scott Grauer-Gray
//November 29, 2010
//Constants for the input parameters given expected motion...

#ifndef INPUT_PARAMS_GIVEN_EXP_MOTION_CONSTS_H
#define INPUT_PARAMS_GIVEN_EXP_MOTION_CONSTS_H

//give the 'index' of each parameter in the input...
const int IMAGE_1_FILE_GIVEN_EXP_MOTION_INDEX = 1;
const int IMAGE_2_FILE_GIVEN_EXP_MOTION_INDEX = 2;

const int MOTION_IMAGE_FILE_SAVE_GIVEN_EXP_MOTION_INDEX = 3;
const int EXPECTED_MOTION_FLO_FILE_GIVEN_EXP_MOTION_INDEX = 4;

const int WIDTH_INPUT_IMAGES_GIVEN_EXP_MOTION_INDEX = 5;
const int HEIGHT_INPUT_IMAGES_GIVEN_EXP_MOTION_INDEX = 6;
const int NUM_BELIEF_PROP_LEVELS_GIVEN_EXP_MOTION_INDEX = 7;
const int NUM_ITERS_PER_BELIEF_PROP_LEVEL_GIVEN_EXP_MOTION_INDEX = 8;
const int DATA_COST_CAP_GIVEN_EXP_MOTION_INDEX = 9;
const int SMOOTHNESS_COST_CAP_GIVEN_EXP_MOTION_INDEX = 10;

const int DATA_COST_WEIGHT_GIVEN_EXP_MOTION_INDEX = 11;
const int CURR_MOVE_INCR_X_GIVEN_EXP_MOTION_INDEX = 12;
const int CURR_MOVE_INCR_Y_GIVEN_EXP_MOTION_INDEX = 13;
const int SAMPLING_LEVEL_GIVEN_EXP_MOTION_INDEX = 14;
const int X_MOVE_MIN_GIVEN_EXP_MOTION_INDEX = 15;
const int X_MOVE_MAX_GIVEN_EXP_MOTION_INDEX = 16;
const int Y_MOVE_MIN_GIVEN_EXP_MOTION_INDEX = 17;
const int Y_MOVE_MAX_GIVEN_EXP_MOTION_INDEX = 18;

const int MOTION_DISPLAY_RANGE_GIVEN_EXP_MOTION_INDEX = 19;
const int GROUND_TRUTH_MOVE_FLO_GIVEN_EXP_MOTION_INDEX = 20;
const int MOTION_MOVE_FLO_GIVEN_EXP_MOTION_INDEX = 21;
const int PROP_CHANGE_MOVE_GIVEN_EXP_MOTION_INDEX = 22;
const int SMOOTHING_SIGMA_GIVEN_EXP_MOTION_INDEX = 23;
const int EST_MOVE_CAP_GIVEN_EXP_MOTION_INDEX = 24;
const int EST_MOVE_WEIGHT_GIVEN_EXP_MOTION_INDEX = 25;

const int NUM_LEVEL_WITHIN_LEV_PYR_HIERARCH_GIVEN_EXP_MOTION_INDEX = 26;

//constant representing 'null'
//const char* NULL_CONST = "null";

#endif //INPUT_PARAMS_GIVEN_EXP_MOTION_CONSTS_H

